# Generated by Django 6.0 on 2025-12-23 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonMarketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("marketplace_id", models.CharField(max_length=32, unique=True)),
                ("country_code", models.CharField(max_length=2)),
                ("active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Amazon-Marktplatz",
                "verbose_name_plural": "Amazon-Marktplätze",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AmazonOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amazon_order_id", models.CharField(max_length=40, unique=True)),
                ("ship_to_country", models.CharField(blank=True, max_length=2)),
                ("purchase_date", models.DateTimeField()),
                ("order_status", models.CharField(max_length=40)),
                (
                    "order_total_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("order_total_currency", models.CharField(max_length=3)),
                (
                    "imported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="amazon.amazonmarketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amazon-Bestellung",
                "verbose_name_plural": "Amazon-Bestellungen",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="AmazonOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "item_price_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("item_price_currency", models.CharField(max_length=3)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amazon_items",
                        to="core.article",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="amazon.amazonorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amazon-Bestellposition",
                "verbose_name_plural": "Amazon-Bestellpositionen",
            },
        ),
    ]
