# Generated by Django 6.0 on 2025-12-23 18:27

from django.db import migrations


def seed_marketplaces(apps, schema_editor):
    marketplace_model = apps.get_model('amazon', 'AmazonMarketplace')
    entries = [
        ('Amazon Deutschland', 'A1PA6795UKMFR9', 'DE'),
        ('Amazon Frankreich', 'A13V1IB3VIYZZH', 'FR'),
        ('Amazon Italien', 'APJ6JRA9NG5V4', 'IT'),
        ('Amazon Spanien', 'A1RKKUPIHCS9HS', 'ES'),
        ('Amazon Niederlande', 'A1805IZSGTT6HS', 'NL'),
    ]
    for name, marketplace_id, country_code in entries:
        marketplace_model.objects.get_or_create(
            marketplace_id=marketplace_id,
            defaults={'name': name, 'country_code': country_code, 'active': True},
        )


def unseed_marketplaces(apps, schema_editor):
    marketplace_model = apps.get_model('amazon', 'AmazonMarketplace')
    marketplace_model.objects.filter(marketplace_id__in=[
        'A1PA6795UKMFR9',
        'A13V1IB3VIYZZH',
        'APJ6JRA9NG5V4',
        'A1RKKUPIHCS9HS',
        'A1805IZSGTT6HS',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_marketplaces, unseed_marketplaces),
    ]
