# Generated by Django 6.0.3 on 2026-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_marketplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="marketplace",
            field=models.CharField(
                choices=[
                    ("amazon", "Amazon"),
                    ("ebay", "Ebay"),
                    ("etsy", "Etsy"),
                    ("easybill", "Easybill"),
                    ("fankultur", "Fankultur Seite"),
                    ("unbekannt", "Unbekannt"),
                ],
                default="unbekannt",
                max_length=30,
            ),
        ),
    ]
