# Generated by Django 6.0.3 on 2026-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_order_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="imported_total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
